/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iuaspirateur;
import aspirateur.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

}
