all:
	cd ProjetJava; \
	cd Aspirateur; \
	gradle fatJar; \
	cd ..; \
	cd DownloadManager; \
	gradle fatJar; \
	cd ..; \
	cd IU; \
	gradle fatJar; \
	cd ..; \
	cd IUAspirateur; \
	gradle fatJar; \
	cd ..;
