/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.sun.tools.javac.util.Pair;

import static org.junit.Assert.*;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.concurrent.CompletableFuture;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    public static CompletableFuture<Path> get(String uri) {
        HttpClient client = HttpClient.newHttpClient();
        HttpRequest request = HttpRequest.newBuilder()
              .uri(URI.create(uri))
              .build();

        return client.sendAsync(request, BodyHandlers.ofFile(Paths.get("body.txt")))
              .thenApply(HttpResponse::body);
    }
    public static void main(String[] args) throws Exception {
    	/*
    	CompletableFuture<Path> cf = get("https://openjdk.java.net/groups/net/httpclient/recipes.html");

    	System.out.print(cf.get());
    	
    	//avoir une page
        Document doc = Jsoup.connect("http://en.wikipedia.org/").get();
        //System.out.println(doc);
        //doc : https://jsoup.org/apidocs/org/jsoup/select/Elements.html
        Elements newsHeadlines = doc.getAllElements();//doc.select("#mp-itn b a"); -> avoir element en particulier
        
        for (Element headline : newsHeadlines) {
        	if(/*headline.absUrl("href").contains("en.wikipedia")*\/headline.attr("href").contains(".css"))
        		System.out.println(headline.attr("href"));
        	/*	
        	log("%s\n\t%s", headline.attr("title") //avoir le titre de la balise
            		, headline.absUrl("href") //avoir les liens des elements
            		);
            		*\/
        }
      */
        Gestionnaire g=new Gestionnaire();
    	g.addLauncher("https://www.irif.fr/~sighirea//cours/reseauxM/java.url.html");
    	for(Pair<String, Launcher.state> p: g.list()) {
    		System.out.println(p.fst+"-"+p.snd+"\n");
    	}
    	g.launch();
        //g.delete();
    	for(Pair<String, Launcher.state> p: g.listOfAll()) {
    		System.out.println(p.fst+"-"+p.snd+"\n");
    	}
    	 
    	 
    }
}
